INSERT INTO TODO_USER (DONE, ID, TARGET_DATE, DESCRIPTION, USER_NAME) VALUES (FALSE, 1001, CURRENT_DATE, 'MY TODO IS MINE', 'ME HU PAPA');

INSERT INTO TODO_USER (DONE, ID, TARGET_DATE, DESCRIPTION, USER_NAME) VALUES (FALSE, 1005, CURRENT_DATE, 'MY TODO IS YOUR', 'ME HU PAPA');

INSERT INTO TODO_USER (DONE, ID, TARGET_DATE, DESCRIPTION, USER_NAME) VALUES (FALSE, 1002, CURRENT_DATE, 'MY TODO IS THERE', 'ME HU PAPA');

INSERT INTO TODO_USER (DONE, ID, TARGET_DATE, DESCRIPTION, USER_NAME) VALUES (FALSE, 1003, CURRENT_DATE, 'MY TODO IS HERE', 'ME HU PAPA');

INSERT INTO TODO_USER (DONE, ID, TARGET_DATE, DESCRIPTION, USER_NAME) VALUES (FALSE, 1004, CURRENT_DATE, 'MY TODO IS HIS', 'ME HU PAPA');